/**
 * Every label a report shows, as a constant. M19, built in P14.
 *
 * Each value is a term from docs/GLOSSARY.md, spelled exactly as it is there.
 * No report definition types a label by hand: it names one of these. A test
 * checks every value appears in the glossary, and that the client's mirror,
 * client/src/features/reports/labels.js, holds exactly the same entries.
 */
export const LABELS = Object.freeze({
  BUSINESS_DATE: 'Business date',
  BILLS: 'Bills',
  COVERS: 'Covers',
  ITEM_TOTAL: 'Item total',
  DISCOUNT: 'Discount',
  NET_SALES: 'Net sales',
  CGST: 'CGST',
  SGST: 'SGST',
  GST: 'GST',
  ROUND_OFF: 'Round-off',
  BILL_TOTAL: 'Bill total',
  AVERAGE_BILL: 'Average bill',
  AVERAGE_PER_COVER: 'Average per cover',
  LINE_TOTAL: 'Line total',
  LINE_DISCOUNT_SHARE: 'Line discount share',
  LINE_NET_SALES: 'Line net sales',
  LINE_GST_SHARE: 'Line GST share',
  MONEY_IN_HAND: 'Money in hand',
  PLATFORM_MONEY: 'Platform money',
  MONEY_RECEIVED: 'Money received',
  ON_HOLD: 'On Hold',
  UNPAID: 'Unpaid bill',
  COLLECTION: 'Collection',
  PAYMENT_METHOD: 'Payment method',
  PLATFORM: 'Platform',
  PLATFORM_ORDER_ID: 'Platform order ID',
  COMMISSION: 'Commission',
  EXPECTED_PAYOUT: 'Expected payout',
  RECEIVED_PAYOUT: 'Received payout',
  PAYOUT_DIFFERENCE: 'Payout difference',
  DISCOUNT_FUNDED_BY: 'Discount funded by',
  CAPTAIN: 'Captain',
  TABLE_TIME: 'Table time',
  AVERAGE_TABLE_TIME: 'Average table time',
  KITCHEN_TIME: 'Kitchen time',
  STATION: 'Station',
  DISCOUNT_REASON: 'Discount reason',
  APPROVED_BY: 'Approved by',
  WASTED_VALUE: 'Wasted value',
  NO_CHARGE_VALUE: 'No Charge value',
  OPENING_FLOAT: 'Opening float',
  CASH_FROM_BILLS: 'Cash from bills',
  CASH_COLLECTIONS: 'Cash collections',
  PAID_IN: 'Paid in',
  PAID_OUT: 'Paid out',
  EXPECTED_CASH: 'Expected cash',
  COUNTED_CASH: 'Counted cash',
  CASH_DIFFERENCE: 'Cash difference',
  INVOICE_SERIES: 'Invoice series',
  SHARE_OF_NET_SALES: 'Share of net sales',
  RANK: 'Rank',
  ORDER_TYPE: 'Order type',
  TABLE: 'Table',
  CATEGORY: 'Category',
  ITEM: 'Item',
  QUANTITY_SOLD: 'Quantity sold',
  CANCELLED_QUANTITY: 'Cancelled quantity',
  ITEMS_CANCELLED: 'Items cancelled',
  QUANTITY: 'Quantity',
  INVOICE_NUMBER: 'Invoice number',
  STATUS: 'Status',
  VOID_REASON: 'Void reason',
  CANCEL_REASON: 'Cancel reason',
  STAGE: 'Stage',
  TIME_ISSUED: 'Time issued',
  TIME_PAID: 'Time paid',
  TIME: 'Time',
  PAID_WITH: 'Paid with',
  TAX_RATE: 'Tax rate',
  TALLY_CODE: 'Tally code',
  HOUR: 'Hour',
  WEEKDAY: 'Weekday',
  PERIOD: 'Period',
  OPEN_TABLES: 'Open tables',
  SAME_WEEKDAY_LAST_WEEK: 'Same weekday last week',
  TURNS_PER_DAY: 'Turns per day',
  PERCENT_OFF: 'Percent off',
  APPLIED_BY: 'Applied by',
  CANCELLED_BY: 'Cancelled by',
  VOIDED_BY: 'Voided by',
  REQUESTED_BY: 'Requested by',
  CLOSED_BY: 'Closed by',
  ACCOUNT: 'Account',
  OPENING_BALANCE: 'Opening balance',
  CHARGED: 'Charged',
  COLLECTED: 'Collected',
  OUTSTANDING: 'Outstanding',
  OLDEST_UNPAID_BILL: 'Oldest unpaid bill',
  FIGURE: 'Figure',
  COUNT: 'Count',
  VALUE: 'Value',
  DISCOUNTED_BILLS: 'Discounted bills',
  CANCELLED_VALUE: 'Cancelled value',
  ITEMS_MADE: 'Items made',
});

export const LABEL_VALUES = Object.freeze(Object.values(LABELS));
